[jobs]
    [jobs.build-cli]
    image = "quay.io/deis/go-dev:v1.6.0"
    tasks = [
        "mkdir -p /go/src/github.com/arschles/helium",
        "cd /go/src/github.com/arschles/helium",
        "cp -R /wd/* .",
        "go get github.com/golang/dep/cmd/dep",
        "dep ensure",
        "go build -o he ./he-cli"
    ]

    [jobs.test-cli]
    image = "quay.io/deis/go-dev:v1.6.0"
    tasks = [
        "mkdir -p /go/src/github.com/arschles/helium",
        "cd /go/src/github.com/arschles/helium",
        "cp -R /wd/* .",
        "go get github.com/golang/dep/cmd/dep",
        "dep ensure",
        "go test ./..."
    ]

[workflows.build]
jobs = ["build-cli", "test-cli"]
