[jobs]
    [jobs.build-cli]
    image = "quay.io/deis/go-dev:v1.6.0"
    tasks = [
        "go build -o he ./he-cli"
    ]

    [jobs.test-cli]
    image = "quay.io/deis/go-dev:v1.6.0"
    tasks = [
        "go test ./..."
    ]

[workflows.build]
jobs = ["build-cli", "test-cli"]
